# Generated by Django 5.1.1 on 2024-10-06 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exoplaneta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("constelacion", models.CharField(max_length=100)),
                ("distancia_light_years", models.FloatField()),
                ("exoplaneta", models.CharField(max_length=100)),
                ("masa", models.FloatField(blank=True, null=True)),
                ("radio", models.FloatField(blank=True, null=True)),
                ("luz", models.CharField(blank=True, max_length=100, null=True)),
                ("periodo_orbital", models.FloatField(blank=True, null=True)),
                ("fecha_descubrimiento", models.DateField(blank=True, null=True)),
                (
                    "metodo_deteccion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "planeta_central",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sistema_solar",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_estrella",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Exoplaneta",
                "verbose_name_plural": "Exoplanetas",
                "ordering": ["exoplaneta"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_response", models.TextField(default="", null=True)),
                ("ai_response", models.TextField(default="", null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.conversation",
                    ),
                ),
            ],
        ),
    ]
